server:
  compression:
    enabled: true
  port: 8080
  tomcat:
    use-relative-redirects: true

#Spring Settings
spring:
  application:
    name: CarSpotter
  profiles:
    default: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    livereload:
      enabled: true

# log level
logging.level:
  org.hibernate.SQL: info
  org.hibernate.type: info
  org.hibernate.type.descriptor.sql: debug
  org.flywaydb.core: debug